name: 'prgx_dbt_models'
version: '1.0.0'
config-version: 2

profile: 'prgx_dbt_models'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  prgx_dbt_models:
    marts:
      finance:
        +materialized: table
